### ISSUE TITLE
Error while building the program. Kindly help on this.

### ISSUE THREAD

**Issue by evertale888** [YWL0720/YOLO_ORB_SLAM3_with_pointcloud_map#8]
While building, i got this error:

YOLO_ORB_SLAM3_with_pointcloud/src/PointCloudMapper.cpp:83:66: error: no matching function for call to ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >::shared_ptr(boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type)’
   83 |             PointCloud::Ptr temp(boost::make_shared<PointCloud>());

My pcl is 1.12.1+dfsg-3build1. Kindly help on this.

**Comment by YWL0720** [comment]
Ok. Tomorrow, I will submit a new piece of code to solve this problem.

**Comment by evertale888** [comment]
> Ok. Tomorrow, I will submit a new piece of code to solve this problem.

Tq again.

**Comment by YWL0720** [comment]
> > Ok. Tomorrow, I will submit a new piece of code to solve this problem.
> 
> Tq again. I look forward to it.

I have committed the lastest code, please try it and see if the above issue still exist.

**Comment by evertale888** [comment]
> > > Ok. Tomorrow, I will submit a new piece of code to solve this problem.
> > 
> > 
> > Tq again. I look forward to it.
> 
> I have committed the lastest code, please try it and see if the above issue still exist.

Ok. i'll get back to you once i finish.

**Comment by evertale888** [comment]
> > > Ok. Tomorrow, I will submit a new piece of code to solve this problem.
> > 
> > 
> > Tq again. I look forward to it.
> 
> I have committed the lastest code, please try it and see if the above issue still exist.

Hello, its still has same error: 

src/PointCloudMapper.cpp:9:50: error: no match for ‘operator=’ (operand types are ‘pcl::PointCloud<pcl::PointXYZRGB>::Ptr’ {aka ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’} and ‘boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type’ {aka ‘boost::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >’})
    9 |     mpGlobalMap = boost::make_shared<PointCloud>();
      |                                                  ^


/src/PointCloudMapper.cpp:11:88: error: no matching function for call to ‘std::shared_ptr<pcl::VoxelGrid<pcl::PointXYZRGB> >::shared_ptr(boost::detail::sp_if_not_array<pcl::VoxelGrid<pcl::PointXYZRGB> >::type)’
   11 |     mpVoxel = pcl::VoxelGrid<PointT>::Ptr (boost::make_shared<pcl::VoxelGrid<PointT>>());


/src/PointCloudMapper.cpp:82:66: error: no matching function for call to ‘std::shared_ptr<pcl::PointCloud<pcl::PointXYZRGB> >::shared_ptr(boost::detail::sp_if_not_array<pcl::PointCloud<pcl::PointXYZRGB> >::type)’
   82 |             PointCloud::Ptr temp(boost::make_shared<PointCloud>());

And i forgot to mention, yesterday i need to include this for another error that already being solved yesterday : #include <boost/make_shared.hpp>

But it give me notes during building and this is one of them:

/usr/include/c++/11/bits/shared_ptr.h:363:9: note: candidate: ‘template<class _Yp> std::shared_ptr<_Tp>::_Assignable<const std::shared_ptr<_Yp>&> std::shared_ptr<_Tp>::operator=(const std::shared_ptr<_Yp>&) [with _Yp = _Yp; _Tp = pcl::PointCloud<pcl::PointXYZRGB>]’
  363 |         operator=(const shared_ptr<_Yp>& __r) noexcept
      |         ^~~~~~~~

**Comment by YWL0720** [comment]
I have committed the lastest code for pcl-1.12, it works on my pc(ubuntu 20.04 pcl-1.12 opencv 4.2), please try it and see if the above issue still exist.

**Comment by ghost** [comment]
> I have committed the lastest code for pcl-1.12, it works on my pc(ubuntu 20.04 pcl-1.12 opencv 4.2), please try it and see if the above issue still exist.

Alright, i get back to you once i try it. 
Btw have u tried run different yolov5 version, or maybe your own trained model? I tried the converted one from pytorch & cant manage to build it. Probably not compatible with the current libtouch or i convert it wrongly?

**Comment by ghost** [comment]
> I have committed the lastest code for pcl-1.12, it works on my pc(ubuntu 20.04 pcl-1.12 opencv 4.2), please try it and see if the above issue still exist.

Alright i managed to build it. But the viewer etc immediately closed after i tried the tum set. Below is the output screen: 

PointCloudMapping thread start!
2023-11-16 15:35:47.529 (   6.953s) [         3FFF640]vtkOpenGLPolyDataMapper:306   WARN| vtkOpenGLPolyDataMapper::GetVertexShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetVertexShaderCode instead.

2023-11-16 15:35:47.529 (   6.953s) [         3FFF640]vtkOpenGLPolyDataMapper:298   WARN| vtkOpenGLPolyDataMapper::SetVertexShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetVertexShaderCode instead.

2023-11-16 15:35:47.529 (   6.953s) [         3FFF640]vtkOpenGLPolyDataMapper:336   WARN| vtkOpenGLPolyDataMapper::GetGeometryShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetGeometryShaderCode instead.

2023-11-16 15:35:47.529 (   6.954s) [         3FFF640]vtkOpenGLPolyDataMapper:328   WARN| vtkOpenGLPolyDataMapper::SetGeometryShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetGeometryShaderCode instead.

2023-11-16 15:35:47.529 (   6.954s) [         3FFF640]vtkOpenGLPolyDataMapper:321   WARN| vtkOpenGLPolyDataMapper::GetFragmentShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetFragmentShaderCode instead.

2023-11-16 15:35:47.529 (   6.954s) [         3FFF640]vtkOpenGLPolyDataMapper:313   WARN| vtkOpenGLPolyDataMapper::SetFragmentShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetFragmentShaderCode instead.

2023-11-16 15:35:47.529 (   6.954s) [         3FFF640]vtkOpenGLPolyDataMapper:306   WARN| vtkOpenGLPolyDataMapper::GetVertexShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetVertexShaderCode instead.

2023-11-16 15:35:47.529 (   6.954s) [         3FFF640]vtkOpenGLPolyDataMapper:298   WARN| vtkOpenGLPolyDataMapper::SetVertexShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetVertexShaderCode instead.

2023-11-16 15:35:47.529 (   6.954s) [         3FFF640]vtkOpenGLPolyDataMapper:336   WARN| vtkOpenGLPolyDataMapper::GetGeometryShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetGeometryShaderCode instead.

2023-11-16 15:35:47.529 (   6.954s) [         3FFF640]vtkOpenGLPolyDataMapper:328   WARN| vtkOpenGLPolyDataMapper::SetGeometryShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetGeometryShaderCode instead.

2023-11-16 15:35:47.529 (   6.954s) [         3FFF640]vtkOpenGLPolyDataMapper:321   WARN| vtkOpenGLPolyDataMapper::GetFragmentShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::GetFragmentShaderCode instead.

2023-11-16 15:35:47.529 (   6.954s) [         3FFF640]vtkOpenGLPolyDataMapper:313   WARN| vtkOpenGLPolyDataMapper::SetFragmentShaderCode was deprecated for VTK 9.0 and will be removed in a future version.  Use vtkOpenGLShaderProperty::SetFragmentShaderCode instead.
Segmentation fault (core dumped)

Looking forward for your reply.

**Comment by ghost** [comment]
> I have committed the lastest code for pcl-1.12, it works on my pc(ubuntu 20.04 pcl-1.12 opencv 4.2), please try it and see if the above issue still exist.

Hello again. Just an update from me, I have build the program without having a warning about vtk this time by updating its lib to 9.2.6 which known to work with pcl 1.12.1. I even reinstall & use the fix build pcl 1.12.1 that known to fix the 'Segmentation fault (core dumped)' error . Now, when running tum, the pcl viewer just shows green & red color then the program stop/close & indicate 'Segmentation fault (core dumped)' error. I use pangolin 0.6. Is it because of pangolin? Which vtk & pangolin ver u used?

**Comment by ghost** [comment]
Just an update:

After manual testing & through gdb, the error kick in when the program come to this line: float d = imDepth.ptr(v)[u];
when calling: pointCloud_new = GeneratePointCloud(mqKeyFrame.front(), mqRGB.front(), mqDepth.front());

For pcl & vtk testing, if i change to constant value like d = 0.5, then i can the see pointcloud being plotted in the viewer. Since its an opencv mat, i try several opencv like ver 4.2 & 4.5.4. Still cannot solve the error.

**Comment by ghost** [comment]
Update: Solved it by building latest vtk. Tq again.
